version: 2

project_name: yara

before:
  hooks:
    - python3 scripts/create_schema_archive.py

builds:
  - id: yara
    main: ./cmd/yara
    binary: yara
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64

archives:
  - id: yara-binaries
    ids:
      - yara
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256
  extra_files:
    - glob: release-artifacts/yara-schemas-v1alpha1.tar.gz

release:
  extra_files:
    - glob: release-artifacts/yara-schemas-v1alpha1.tar.gz

changelog:
  disable: true
